excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://cdainmiller.github.io
title: Dain's Brain
email: miller.dain@gmail.com
author: Dain Miller
description: Robotic intentions
paginate: 3
google_analytics: 
