excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://cdainmiller.github.io
title: Ctrl-Dev
email: miller.dain@gmail.com
author: Dain Miller
description: Ctrl-Dev
paginate: 100
google_analytics: 
